name: echoar_package
description: echoAR is a cloud-based 3D-first content management system (CMS) and delivery network (CDN) that provides server-side solutions to help scale augmented and virtual reality (AR/VR) applications. Our 3D-ready cloud platform helps manage & deliver AR/VR content to apps & devices everywhere. This is a plugin which makes it easier to get your assets from echoAR.
version: 0.0.1+2
homepage: https://www.echoar.xyz

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.10
  http: ">=0.12.1 <0.14.0"
  archive: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  